before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: .
    binary: dependency-guardian
archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    groups:
      - title: Features
        regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
        order: 0
      - title: 'Bug fixes'
        regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
        order: 1
      - title: Others
        order: 999