name: 'Dependency Guardian Action'
description: 'Analyzes pull request dependencies and posts an impact report.'
author: 'Cosmos'
inputs:
  github-token:
    description: 'The GITHUB_TOKEN secret. Required for API access.'
    required: true
runs:
  using: "composite"
  steps:
    - name: Download Dependency Guardian
      run: |
        VERSION=$(echo ${{ github.action_ref }} | sed 's/refs\/tags\///')
        curl -L -o dependency-guardian.tar.gz "https://github.com/cosmos/dependency-guardian/releases/download/${VERSION}/dependency-guardian-$(uname -s | tr '[:upper:]' '[:lower:]')-$(uname -m | sed 's/x86_64/amd64/').tar.gz"
        tar -xzf dependency-guardian.tar.gz
        sudo mv dependency-guardian /usr/local/bin/
        rm dependency-guardian.tar.gz
      shell: bash
    - name: Get PR number
      id: get_pr_number
      run: echo "PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")" >> $GITHUB_ENV
      shell: bash
    - name: Run Dependency Guardian
      run: dependency-guardian analyze
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }} 